#!/bin/bash
loop=1;

function dir(){
	cnt=0
	result=$( $workingD | ls -R )
	for i in $result; do
		if [[ "${i}" != ".:" ]]; then
			echo -n "|"
			if [[ ${i:(-1)} == ":" ]]; then
				cnt=$( echo \"${i}\" | grep -o / | wc -l )
			fi
			for (( j=1; j <= $cnt; j++)); do
				echo -n "	|"
			done
			echo ${i} | sed -E "s/(.+\/)//" | sed "s/://" 
		fi
	done
}

function pri(){
	echo "----------------------------------------------------";
        pwd 
        echo "----------------------------------------------------";
}

while [ $loop ];
do
	pri;

	read -p "$ " name;
	
	if [[ "${name}" == "ls" ]]; then
		dir . 1;
	else
		eval ${name}
	fi
	

done
